# Generated by Django 3.2.18 on 2023-05-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='id',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
